# Generated by Django 4.1.3 on 2022-11-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seller", "0001_initial"),
        ("customer", "0008_alter_profile_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="shop_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("category", models.CharField(max_length=10, null=True)),
                ("in_interact", models.CharField(max_length=100, null=True)),
                ("ex_interact", models.CharField(max_length=64, null=True)),
                ("payment", models.CharField(max_length=100, null=True)),
                (
                    "seller_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop",
                        to="seller.seller_detail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_queue", models.IntegerField(default=0)),
                ("numshop", models.IntegerField(default=0)),
                ("expire", models.IntegerField(default=0)),
                (
                    "shop",
                    models.ManyToManyField(
                        blank=True, related_name="addqueue", to="myshop.shop_detail"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(null=True)),
                ("description", models.CharField(max_length=300)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rev",
                        to="customer.profile",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rev",
                        to="myshop.shop_detail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=64)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                ("product_im", models.ImageField(upload_to="images/")),
                ("count", models.IntegerField(null=True)),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prod",
                        to="myshop.shop_detail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="customer.profile",
                    ),
                ),
                (
                    "prod",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered",
                        to="myshop.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="myorder",
                        to="myshop.shop_detail",
                    ),
                ),
            ],
        ),
    ]
