# Generated by Django 4.1.3 on 2022-11-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop_detail",
            name="interact",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=64)),
                ("price", models.IntegerField(null=True)),
                ("product_im", models.ImageField(upload_to="images/")),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop",
                        to="myshop.shop_detail",
                    ),
                ),
            ],
        ),
    ]
