# Generated by Django 4.1.1 on 2022-11-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop_detail",
            name="category",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="shop_detail",
            name="interact",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
