# Generated by Django 4.1.3 on 2022-11-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="review",
        ),
    ]
