# Generated by Django 4.1.3 on 2022-11-06 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_delete_myorder"),
        ("myshop", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name="MyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="customer.profile",
                    ),
                ),
                (
                    "prod",
                    models.ManyToManyField(
                        blank=True, related_name="ordered", to="myshop.product"
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="myorder",
                        to="myshop.shop_detail",
                    ),
                ),
            ],
        ),
    ]
