# Generated by Django 4.1.3 on 2022-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0002_alter_round_expire"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="start",
            field=models.DateTimeField(null=True),
        ),
    ]
