# Generated by Django 4.1.3 on 2022-11-06 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0003_product_count_alter_product_price_myorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myorder",
            name="count",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
