# Generated by Django 4.1.2 on 2022-11-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_alter_shop_detail_category_and_more'),
        ('myshop', '0003_alter_product_shop'),
    ]

    operations = [
    ]
