# Generated by Django 4.1.3 on 2022-11-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0003_alter_product_shop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop_detail",
            name="interact",
        ),
        migrations.AddField(
            model_name="shop_detail",
            name="ex_interact",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="shop_detail",
            name="in_interact",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shop_detail",
            name="category",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
