# Generated by Django 4.1.3 on 2022-11-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0004_alter_myorder_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myorder",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
