# Generated by Django 4.1.2 on 2022-11-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_merge_20221105_2101'),
        ('myshop', '0004_remove_shop_detail_interact_shop_detail_ex_interact_and_more'),
    ]

    operations = [
    ]
