# Generated by Django 4.1.3 on 2022-11-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0005_alter_myorder_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="myorder",
            name="bill",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="shop_detail",
            name="payment",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
