# Generated by Django 4.1.3 on 2022-11-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0005_merge_20221105_2106"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop_detail",
            name="interact",
        ),
    ]
