# Generated by Django 4.1.3 on 2022-11-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0006_myorder_bill_shop_detail_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myorder",
            name="prod",
        ),
        migrations.AddField(
            model_name="myorder",
            name="prod",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered",
                to="myshop.product",
            ),
        ),
    ]
