# Generated by Django 4.1.1 on 2022-11-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talard", "0004_alter_review_options_alter_review_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_rating",
            field=models.IntegerField(),
        ),
    ]
