# Generated by Django 4.1.1 on 2022-11-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talard", "0006_rateus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rateus",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
