# Generated by Django 4.1.3 on 2022-11-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_profile_delete_customer_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="c_name",
                        to="customer.profile",
                    ),
                ),
            ],
        ),
    ]
