# Generated by Django 4.1.3 on 2022-11-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_myorder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyOrder",
        ),
    ]
